resolver: lts-13.22

docker:
  enable: false
  image: fastest-matrices-dev:latest

packages:
- .
# Dependency packages to be pulled from upstream that are not in the resolver
# using the same syntax as the packages field.
# (e.g., acme-missiles-0.3)
extra-deps: 
- git: https://github.com/tonyday567/numhask.git
  commit: 9e10bab5d1a2b01e202da669c5f0391a47b84f02
  subdirs: 
    - numhask
    - numhask-prelude
    - numhask-space
    - numhask-array

- git: https://github.com/DataHaskell/dh-core.git
  commit: 545c4b974dd35d971dc400836878c15e1c41ee07
  subdirs: 
    - dense-linear-algebra

- git: https://github.com/scravy/bed-and-breakfast.git
  commit: e900464394bb13edeb7a439ec758f059dc4712db

- git: https://github.com/haskell-numerics/hmatrix.git
  commit: 5e4bb9a51645dd26e4d506ea9aa78c60ccfa138a
  subdirs:
    - packages/base

- scheduler-1.4.0@sha256:b182be9a7b84e1dba02dac761c3f4e204521d0f779d72d86040789d5aaadf92a,2833
- git: https://github.com/lehins/massiv.git
  commit: 3a6353086bbae95425d1acf240d21a9feeeb06c6
  subdirs:
    - massiv

- dimensions-1.0.1.1

allow-newer: true
# Override default flag values for local packages and extra-deps
# flags: {}

# Extra package databases containing global packages
# extra-package-dbs: []

# Control whether we use the GHC we find on the path
# system-ghc: true
#
# Require a specific version of stack, using version ranges
# require-stack-version: -any # Default
# require-stack-version: ">=1.9"
#
# Override the architecture used by stack, especially useful on Windows
# arch: i386
# arch: x86_64
#
# Extra directories used by stack for building
# extra-include-dirs: [/path/to/dir]
# extra-lib-dirs: [/path/to/dir]
#
# Allow a newer minor version of GHC than the snapshot specifies
# compiler-check: newer-minor
